### ISSUE TITLE
Separate Live Chat site

### ISSUE THREAD

**Issue by farshid3003** [parle-io/parle#16]
Is it possible to put live chat on a separate site and send traffics to live chat site for farms and sites with large amount of request. 
and another issue is making messages smaller an improve performance.
(for an instance using attributes for model to make it smaller.)

**Comment by dstpierre** [comment]
If you are running in a multiple instances scenario you would need to use a "sharable" SignalR hub. In Azure for instance that could be in a Service Bus. At this time, LCSK do not support multiple instances.

As for having the chat widget on another site, you would have to enable CORS (both in the SignalR hub and the client side).

Not sure I understand what you mean regarding having the messages smaller / attributes. Can you elaborate on that?

Thanks

**Comment by bctan73** [comment]
Anyone has done this successfully? Mind to share some reference here? Thanks.

**Comment by dstpierre** [comment]
I'm closing this since LCSK is changing to a more robust customer communication app.

Thank you for your interests in LCSK and I hope Parle will be ready soon so you can have a look at it.
