### ISSUE TITLE
When visitor changes pages, a new data-id is created each time.

### ISSUE THREAD

**Issue by beefydog** [parle-io/parle#22]
I noticed that a new row in the Real Time Visits is created for the same visitor as they view different pages of the website, each row has a different data-id  - this can be confusing to the Agents as, if they click an engage in chat link (that was created by a prior page), the message goes nowhere and the visitor will not see it. Only the very last row link will work (for that unique visitor).
On the visitor's side, they lose the conversation if they switch to another page, but it still remembers to continue the chat with the correct agent.
On the Agent's chat window, the system reports "The visitor closed the connection" then immediately reports "The visitor is now on http:// .... " when the visitor switches pages.
Is there a way around this?

**Comment by dstpierre** [comment]
At this time there's none, SignalR assign a new connection id when the page is loaded. This is a known issue and for now the best I could do with the time I have was to try to re-start the same conversation with the same agent

**Comment by dstpierre** [comment]
I'm closing this since LCSK is changing to a more robust customer communication app.

Thank you for your interests in LCSK and I hope Parle will be ready soon so you can have a look at it.
