### ISSUE TITLE
when the administrator escaped or F5 http://domain.com/lcsk/agent.html, it had an error that the administrator could not chat nor see what client on the website. So they noticed me

### ISSUE THREAD

**Issue by qgate** [parle-io/parle#25]
Hello, I successfully installed it on my asp.net mvc5 website. 
After I logged in as an agent and then click agent panel link, or if I close the browser tab, the session got lost, and I couldn't log in as the same agent. However from the front end visitor page, the visitor still see the chat window, he can still send message to that agent, but there is no way to see the message from the back end(the agent page) Any help will be appreciated.
Thanks

**Comment by dstpierre** [comment]
This is a "known" issue, you have to set yourself as offline before closing / refreshing the agent page. You should have a prompt that ask you to set yourself offline when doing so though, it was added in the last release.

**Comment by qgate** [comment]
I'm on this page  http://domain.com/lcsk/agent.htm
Agent name: CSKH
Agent Password: admin
At first I signed in  http://domain.com/lcsk/agent.htm , it ran normally. But when I escaped and signed in again with Agent Name: CSKH, Agent Password: admin
Then I can't chat with my customer

I didn't see any customers who were connecting with my website
They sent me messages but I didn't see any things

**Comment by dstpierre** [comment]
Like I was saying, you **must** set yourself offline before closing / refreshing the agent.html page, or it will not work properly. This is the only workaround so far.

**Comment by qgate** [comment]
I did it as you said, I set myself offline before closing / refreshing the agent.html page.  But when I refreshed it, the user had chatted with me f5 could not see anymore. Although the agent set offline before closing/refreshing

**Comment by dstpierre** [comment]
Once an agent set them as offline the communication is closed with the visitor, they saw a message like "agent closes the chat". I'm not totally certain what is your test case here?

1. When an agent is online and try to close or refresh the page, their should be a warning message that request them to set as offline before closing the page.

2. If you set yourself as offline during a conversation and reset yourself as online you will not be able to continue that conversation, why did the agent would do that in a middle of a conversation?

3. This aspect of the app is a known issue, I would simply advise that you do not hit F5 or try to close your agent.html page specially in a middle of a conversation.

You're welcome to contribute if you would like to have a look and fix that scenario.

**Comment by qgate** [comment]
Fix: 
- After agent setting offline, Agent logged in again and the user refresh browser tab can be continue chatting with agent
- Agent needn't setting offline, when user  refresh brower tab, it can be continue chatting with agent


if (Agents.Any(x => x.Key == name))
{
//Change Old Chats
if (ChatSessions.Any(c => c.Value == Agents[name].Id))
{
var chatSessionId = ChatSessions.First(c => c.Value == Agents[name].Id).Key;
ChatSessions[chatSessionId] = Context.ConnectionId;
}
//Assign new connection ID to old agent
Agents[name].Id = Context.ConnectionId;
agent = Agents[name];

                Clients.Caller.loginResult(true, agent.Id, agent.Name);

                Clients.All.onlineStatus(Agents.Count(x => x.Value.IsOnline) > 0);
            }

**Comment by qgate** [comment]
I have added the code above but when agent setting offline, then logged in again and user refeshed browser tab, agent was online but user didn't see "chat with us"

**Comment by jhermiz** [comment]
@qgate - Please mark this issue closed if you resolved it.  Also was a pull request put in for this or are you locally fixing?  Either way you need to close this issue.

**Comment by qgate** [comment]
My problem haven't been solved, the error above haven't been fixed.

**Comment by dstpierre** [comment]
I'm closing this since LCSK is changing to a more robust customer communication app.

Thank you for your interests in LCSK and I hope Parle will be ready soon so you can have a look at it.
