### ISSUE TITLE
Send file option in chat window

### ISSUE THREAD

**Issue by touseef4pk** [parle-io/parle#28]
Hi dstpierre,
 Thanks for such a nice implementation. I have implemented chat window on my demo application which is working fine. I want to include send file option where visitor can b able to send file to agent or agent can send file to visitor. How can i achieve that can u plz guide me on that ? 
By the way, I am using asp.net web forms. 

Thanks in advance

**Comment by jhermiz** [comment]
You will need to add a file upload capability onto the div.

`<input type="file" id="input">`

You can then capture this file through some sort of event.

**Comment by dstpierre** [comment]
I'm closing this since LCSK is changing to a more robust customer communication app.

Thank you for your interests in LCSK and I hope Parle will be ready soon so you can have a look at it.
