### ISSUE TITLE
Connection must be started before data can be sent. Call .start() before .send()

### ISSUE THREAD

**Issue by qgate** [parle-io/parle#29]
I was chatting with the client, after 5-10 minutes the connection was lost. Then I used Firebug to check out the errors, I tried to send messages to the client but it noticed that "Connection must be started before data can be sent. Call .start() before .send()". Meanwhile, the client still saw me online on his homepage and keep chatting with me but messages could not be sent 
I cant connect with my client but when he clicked in the website, it still has the tab "chat with us"

![nh ch p man hinh 2015-05-14 luc 11 46 37 ch](https://cloud.githubusercontent.com/assets/4434512/7636872/078bcd02-fa94-11e4-87de-206637d5bf55.png)
![nh ch p man hinh 2015-05-14 luc 11 48 17 ch](https://cloud.githubusercontent.com/assets/4434512/7636864/fe7e4cd0-fa93-11e4-9b7d-40545f26720c.png)

**Comment by dstpierre** [comment]
I'm closing this since LCSK is changing to a more robust customer communication app.

Thank you for your interests in LCSK and I hope Parle will be ready soon so you can have a look at it.
