### ISSUE TITLE
Send the transcript via email (Question)

### ISSUE THREAD

**Issue by michaelhidalgo** [parle-io/parle#34]
Is is possible to send the transcript of the conversation via email address?

**Comment by dstpierre** [comment]
It's not implemented, but you may add the feature if you want.

Since the messages are not saved on the server, you would have to start from the message on the client side.

**Comment by jhermiz** [comment]
If you are working with sql server please take a look at my forked version: https://github.com/jhermiz/lcsk  Here i provide a .sql file with the CREATE table script and I modified chat.js to make an ajax call to load this table with the message.  With this information you can easily export the data to either a text file or a reporting services report and add it as a "link" when the agent "disconnects" the chat.

**Comment by dstpierre** [comment]
I'm closing this since LCSK is changing to a more robust customer communication app.

Thank you for your interests in LCSK and I hope Parle will be ready soon so you can have a look at it.
