### ISSUE TITLE
No admins but still "chat with us" in the chat bar

### ISSUE THREAD

**Issue by johnfcporto** [parle-io/parle#39]
I'm running the project in localhost.

I don't have admins logged in but the chat bar displays "chat with us"

**Comment by jhermiz** [comment]
Something is wrong with your onlineStatus.  Ensure you've cleared all your cache / history and all agents are logged off.  The chathub has a check if any agents are logged on and if so calls `onlineStatus()` (this method is found in chat.js).  Try to trace this / debug this method to see why.

**Comment by johnfcporto** [comment]
the test case is this:
1. run localhost, as a visitor.
2. open localhost, now as an agent(...i go to lcsk/agent.html) enter name and pass.
3. logged in as agent
4. on visitor front end it turns to "chat with us"
5. close agent browser
6. still have chat with us

The first problem is the one above.

But if i run localhost again, connect as an agent, and put a breakpoint on method agentConnect(),
it turns out that list of agent still has the one i logged in before..why is this happening? when i close the agent browser it's not supposed to disconnect that agent?

**Comment by jhermiz** [comment]
You h ave stated the issue yourself, you said "close agent browser" that is exactly your problem you are not supposed to close the agent browser...you are supposed to LOG OFF of the agent browser.  There is a "SET OFFLINE" link in the agent browser..you have to click that as an agent.  If you simply close the browser how do you expect the flag to be set that states you are now not able to support?  

The solution is to click the link found on the top right that says SET OFFLINE.  This is why when you close the browser you get a javascript message.

**Comment by johnfcporto** [comment]
Hmm I see... But i found another issue.

1. run localhost as a visitor
2. run localhost as an agent
3. logged in as agent
4. on visitor front end it turns to "chat with us"
5. I(admin) talk with visitor
6. then i set me(admin) offline
7. visitor front end turns to "contact us"
8. run another localhost as an agent(another name)
9. visitor front end still is "contact us"

note: the visitor is always "the same", the same browser

**Comment by jhermiz** [comment]
@johnfcporto, You need to ensure the agent names are unique, again I ask you to read the documentation and understand the code, you are pulling the trigger too soon.  An easy test case can demonstrate what you have just mentioned.

Do the same thing you just mentioned but log in with a different agent name.

**Comment by johnfcporto** [comment]
but the test case I describe earlier it's diferent. I login with agent name( jon, for example), then i set offline, i login with another agent(ric, for example), but the visitor does not get "chat with us".. 

Another question I have is:
I log in agent name: jon, i set offline and I close the browser.

Imagine I want to log in with agent name jon again? I can't...

**Comment by dstpierre** [comment]
There's certainly some clean-up to be done it that area. I will admit that I did not test all those scenarios :). LCSK is a quick implementation, a "starter kit".

I would be more than happy to review any pull request (I'm not putting much time on lcsk these days), but I'll do my best to review and publish new / improved version.

**Comment by jhermiz** [comment]
@dstpierre / @johnfcporto - I tested this exact scenerio.  I created an agent "jon" I then set them offline, I then created another agent (ric) and my visitor sees "chat with us".  This works perfectly fine for me.  Your other test case will not work as "jon" although is offline is still an agent.  You can either change the implementation to use unique guids or just not use the same agent name.  This can be tested as well in agent.html using an ajax call.

**Comment by johnfcporto** [comment]
yeah, i think there should be an option to disconnect agent. Because if you want to login again with an agent name that has been choosen before you can't. i'm doing it right now

**Comment by dstpierre** [comment]
I'm closing this since LCSK is changing to a more robust customer communication app.

Thank you for your interests in LCSK and I hope Parle will be ready soon so you can have a look at it.
