### ISSUE TITLE
Some problems with setting offline/online agents

### ISSUE THREAD

**Issue by johnfcporto** [parle-io/parle#41]
I run some test case and I believe I found some issues:

Test Case 1:
1. Run Localhost, go to visitor page.
2. Run Localhost, go to agent page.
3. Login as agent.
4. Visitor get "chat with us".
5. I set first agent offline and close browser.
6. Visitor get "contact us"
7. Login as agent ( diferent name from the above).
8. Visitor still gets "contact us"

I believe this is an issue.

Test Case 2:
1. Run Localhost and created 2 agents.
2. set them offline and close the 2 browsers.
3. stop localhost.
4. Run localhost again.
5. create another agent, and the list of agents still has the 2 ones I created before..

How to fix this?

Test Case 3:
1. Login as agent(name: jon)
2. Run localhost as visitor
3. Visitor talk with jon
4. agent jon set offline and close
5. If i want login with the same agent name i can't

I think it should be possible..

**Comment by jhermiz** [comment]
I tested all three cases that you mentioned and all of mine worked as expected.  I think you have some further issues due to changes you might have made?  Out of the box forking this project or just downloading this project all 3 test cases work as expected.

**Comment by chrismaliszewski** [comment]
I have similar Case 3 issue on a clear solution (without any changes in code, just created an agent). I use newest version of Chrome (53) and Firefox (43)

Scenario:
-turn off IIS Express and solution to make a clear start,
-run solution, contact us! shows that there is not agent (ok),
-open new browser, login in as an agent (client sees that agent is in),
-as agent click LCSK - Agent Panel test and Leave Page (user doesn't see that agent left),
-log in again,
-from now on chat doesn't work, messages are not passed even when user reloads page.

Any idea? I'll try to look on this issue later, but maybe someone already found the solution.
Thank you in advance!

**Comment by dstpierre** [comment]
I'm closing this since LCSK is changing to a more robust customer communication app.

Thank you for your interests in LCSK and I hope Parle will be ready soon so you can have a look at it.
