### ISSUE TITLE
When <machinekey validation> added to the webconfig it says unable to connect.

### ISSUE THREAD

**Issue by ma85855** [parle-io/parle#42]
When I add machineKey validation="3DES" to my web.config file then the connection fails. Without the machinekey everything works normally. But to encrypt the viewstate that machinekey validation is necessary for me. So how to solve this problem?

**Comment by dstpierre** [comment]
I'm closing this since LCSK is changing to a more robust customer communication app.

Thank you for your interests in LCSK and I hope Parle will be ready soon so you can have a look at it.
