### ISSUE TITLE
Error undefined 'hub'

### ISSUE THREAD

**Issue by aruedaAst** [parle-io/parle#43]
Hello,

I have an issue after install LCKS chat. I've done:
- I've created a new web application (Visual Studio 2013 .NET 4.5) MVC template
- LCKS Installed  from NUGET
-  "[assembly: OwinStartup(typeof(" changed from Startup.cs to my current namespace
- scripts added in "index.cshtml"
   <script src="~/LCSK/assets/js/jquery-2.1.1.min.js" type="text/javascript"></script>
   <script src="~/LCSK/assets/js/jquery.signalR-2.1.1.min.js" type="text/javascript"></script>
   <script src="/signalr/hubs" type="text/javascript"></script>
   <script src="~/LCSK/chat.js" type="text/javascript"></script>
- Run my application
   Exception (all browsers): Error chat.js Line 69: 'hub' undefined ($.connection.hub.start())
- 'Contact us' appears but Chatbox doesn't

Thanks in advance

**Comment by dstpierre** [comment]
I'm closing this since LCSK is changing to a more robust customer communication app.

Thank you for your interests in LCSK and I hope Parle will be ready soon so you can have a look at it.
