### ISSUE TITLE
New feature on Closing agent browser

### ISSUE THREAD

**Issue by johnfcporto** [parle-io/parle#44]
I want to implement some new features, but i have some doubts on how to do it.

In my agent page, i added a logout button. When I press this button, it calls a server side method, that disconnects that agent, removes that agents from the list, and show me the login form again.

Now i want to add this feature:

Imagine the agent (jon) is chatting with a visitor and he closes the browser withou setting offline..

I want to remove that agent from the list of agents and notify the visitor that the agent has gone.

How can I do it?

**Comment by dstpierre** [comment]
I'm closing this since LCSK is changing to a more robust customer communication app.

Thank you for your interests in LCSK and I hope Parle will be ready soon so you can have a look at it.
