### ISSUE TITLE
How to change the  DefaultConnection database

### ISSUE THREAD

**Issue by WinmanSoftwarePvtLtd** [parle-io/parle#49]
Hi,
Nice project.
It is mentioned in the web.config file that we can change the database reference from default one. I want to store all the data of chat in my MS-SQL server. Can you provide the database structure required to your project ?

**Comment by dstpierre** [comment]
I'm closing this since LCSK is changing to a more robust customer communication app.

Thank you for your interests in LCSK and I hope Parle will be ready soon so you can have a look at it.
