### ISSUE TITLE
I'm considering a brand new project and LCSK is not maintained anymore

### ISSUE THREAD

**Issue by dstpierre** [parle-io/parle#53]
First I would like to say that LCSK in its .NET version is not maintained anymore. I'm no  more a .NET developer for a long time now and this project already exceeded what it was supposed to be at first in 2007, which was a simple getting started project to build a more complete live chat app.

Thanks to everyone that has been involved, tried the project and contribute.

I have another project I'm currently evaluating. I always liked live chat and offering A1 support to users and website visitors. I also know there is not much open source projects that offer similar features of product like [Intercom](https://intercom.io), [Drift](https://www.drift.com). This might be something I would like to build and use [Live Coding](https://www.livecoding.tv/) at the same time.

An ambitious project for sure, and some might ask why open source this instead of building a SaaS. Well, I already have a startup [Roadmap](https://roadmap.space) and does not really want to enter that market and compete. It's just something I'd like to build :)

So depending on reactions and demand, I'm kind of trying to validate this open source project before building it.

Please let me know if it's something you would use.
Thanks

**Comment by jhermiz** [comment]
Would you mind if I take over the LCSK?

I have been involved in it for some time now.

**Comment by dstpierre** [comment]
I was actually thinking of renaming and starting a new branch and at some point merge into master.

The project I'm considering would be lot more user friendly thant LCSK and would deploy to a DigitalOcean droplet easily.

In any case @jhermiz I will keep that in mind for sure depending of the decision I take.

Thanks

**Comment by jhermiz** [comment]
No problem I can help if you like.

I have taken a local copy of lcsk and integrated it into a full stack using sql server as the back end.

The chat itself can then be stored into a database and file uploads and downloads can be made right within lcsk.

**Comment by dstpierre** [comment]
> No problem I can help if you like.

@jhermiz sure. I'm preparing to start the first live stream session. The Livecoding.tv channel is [here](https://www.livecoding.tv/dstpierre).

First thing that will be built is the live chat / in-app messaging component, so this will be similar to what LCSK was. But with a 2016 feel to it.

I would suggest keep an eye on the repo and if you are interested in checking the live stream / sharing, would appreciate :). From there I will start using ZenHub to handle what to do and any pull request will be welcome.

**Comment by hbakhtiyor** [comment]
any updates? :)

**Comment by dstpierre** [comment]
Hi @hbakhtiyor yes actually, I have been distracted in the last months, but I have plans to start working on the product regularly.

**Comment by hbakhtiyor** [comment]
great to hear

**Comment by jhermiz** [comment]
I don’t think it was a good idea to remove the original lcsk chat client.

We still use it and suddenly losing it completely on github I believe to be a mistake.


Why can we not just keep lcsk on github and create a new “project” on github for your new project?

**Comment by dstpierre** [comment]
@jhermiz the original lcsk is still in the lcsk branch, feel free to fork this if you want and continue this project if you like. For me I started LCSK in 2007 and I think this new project is really the v2 of this idea I had back than.

If you are using LCSK you'll most certainly love Parle since the first module that will be available will be the messenger, so kind of similar to LCSK but with a 2017 feels.

In any case let me know if I can do anything to get you started if you want to continue LCSK, but I would also suggest that you keep an eye on Parle as it will be way better :)

**Comment by jhermiz** [comment]
No problem I will help with parle just as I helped with lcsk.
